[package]
name = "imgik"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.10"
png = "0.17.8"
reqwest = { version = "0.11.18", features = ["blocking"] }
rulinalg = "0.4.2"
